steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ps-app', '.']

images:
  - 'eu.gcr.io/$PROJECT_ID/ps-app:latest'
  - 'eu.gcr.io/$PROJECT_ID/ps-app:$SHORT_SHA'

tags: ['ps-app']