steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: /bin/sh
    args: ['-c', 'gcloud auth print-access-token > access_token.txt']

  - name: mikefarah/yq
    dir: helm
    args: ['yq', 'w', '-i', 'Chart.yaml', 'appVersion', $SHORT_SHA]


  - name: bash
    dir: helm
    args: ['cat', 'Chart.yaml']
#  - name: gcr.io/cloud-builders/docker
#    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ps-app', '.']



#images:
#  - 'eu.gcr.io/$PROJECT_ID/ps-app'

tags: ['ps-app']