steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    entrypoint: /bin/sh
    args: ['-c', 'gcloud auth print-access-token > access_token.txt']

  - name: bash
    args: ['ls', '-lah']

  - name: bash
    args: ['cat', 'access_token.txt']
#  - name: gcr.io/cloud-builders/docker
#    args: ['build', '-t', 'eu.gcr.io/$PROJECT_ID/ps-app', '.']



#images:
#  - 'eu.gcr.io/$PROJECT_ID/ps-app'

tags: ['ps-app']