---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
  labels:
    app: {{ .Release.Name }}
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ .Release.Name }}
              servicePort: {{ .Values.service.port }}