apiVersion: v1
name: ps-api
version: 0.0.1
appVersion: 0.0.1
description: The Helm chart to deploy ps-app, the paymentsystems product visualiser.
maintainers:
  - name: Simon Aquino
    email: simon.aquino@gmail.com